### ISSUE TITLE
For publishing commands on UR simulation gazebo & rviz robot IP is same as PC IP?

### ISSUE THREAD

**Issue by lakshmip001** [ros-industrial/robot_movement_interface#10]
I want to publish commands on simulation before publishing on real robot. Can I know what would be the IP address of Robot?

**Comment by maclo4** [comment]
Did you ever figure this out?

**Comment by pablo-quilez** [comment]
Hi @maclo4, the simulation is exactly like the robot controller. The answer to your question is yes, you can use the official UR robot simulator and visualize in RVIZ the movement. You need to use the IP of the computer where is the simulation running. The IP address of the real controller can be changed to desired static or to DHCP. I hope this helps!
