### ISSUE TITLE
Can I use this package with ursim3.5? 

### ISSUE THREAD

**Issue by lakshmip001** [ros-industrial/robot_movement_interface#13]
I am using this package with URsim but unable to decide on whats the difference between simulators 3.0 to 3.5, when I try to use i get different errors and different output. which simulator is best to use?

**Comment by pablo-quilez** [comment]
Hello,

UR had the tendency to change the communication (robot-computer) protocol
between different versions. If I am correct, 3.1 should be working fine.

Regards,
Pablo

2018-08-31 6:30 GMT+02:00 lakshmip001 <notifications@github.com>:
